<div id="head_menu">
  <table>
    <tr>
      <td>
        <form method="get" action="index.html">
          <input type="submit" class="menu_button" value="Main" title="index.html" id="menu_main" style="width:80px">
        </form>
      </td>
      <td>
        <form method="get" action="but_bpm.htm">
          <input type="text" name="RFFE_ADDR" value="<% webmapGetParam("RFFE_ADDR"); %>" class="debug_1">
          <input type="text" name="BPM_ADDR" value="<% webmapGetParam("BPM_ADDR"); %>" class="debug_1">
          <input type="text" name="CFG_RD_ADDR"     value="<% webmapGetParam("CFG_RD_ADDR"    ); %>" class="debug_1">
          <input type="text" name="CFG_WR_ADDR"      value="<% webmapGetParam("CFG_WR_ADDR"     ); %>" class="debug_1">
          <input type="text" name="CFG_SN_ADDR"  value="<% webmapGetParam("CFG_SN_ADDR" ); %>" class="debug_1">
          <input type="text" name="ADC_ADDR"     value="<% webmapGetParam("ADC_ADDR"    ); %>" class="debug_1">
          <input type="text" name="BPM_COMM_ADDR"  value="<% webmapGetParam("BPM_COMM_ADDR" ); %>" class="debug_1">
          <input type="text" name="QDR_ADDR"  value="<% webmapGetParam("QDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DDR_ADDR"  value="<% webmapGetParam("DDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DEVICE"       value="<% webmapGetParam("DEVICE"      ); %>" class="debug_1">
          <input type="submit" class="menu_button" value="BPM" title="but_bpm" id="menu_bpm" style="width:80px">
        </form>
      </td>
      <td>
        <form method="get" action="but_rffe.htm">
          <input type="text" name="RFFE_ADDR" value="<% webmapGetParam("RFFE_ADDR"); %>" class="debug_1">
          <input type="text" name="BPM_ADDR" value="<% webmapGetParam("BPM_ADDR"); %>" class="debug_1">
          <input type="text" name="CFG_RD_ADDR"     value="<% webmapGetParam("CFG_RD_ADDR"    ); %>" class="debug_1">
          <input type="text" name="CFG_WR_ADDR"      value="<% webmapGetParam("CFG_WR_ADDR"     ); %>" class="debug_1">
          <input type="text" name="CFG_SN_ADDR"  value="<% webmapGetParam("CFG_SN_ADDR" ); %>" class="debug_1">
          <input type="text" name="ADC_ADDR"     value="<% webmapGetParam("ADC_ADDR"    ); %>" class="debug_1">
          <input type="text" name="BPM_COMM_ADDR"  value="<% webmapGetParam("BPM_COMM_ADDR" ); %>" class="debug_1">
          <input type="text" name="QDR_ADDR"  value="<% webmapGetParam("QDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DDR_ADDR"  value="<% webmapGetParam("DDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DEVICE"       value="<% webmapGetParam("DEVICE"      ); %>" class="debug_1">
          <input type="submit" class="menu_button" value="RFFE" title="but_rffe" id="menu_bpm" style="width:80px">
        </form>
      </td>
      <td>
        <form method="get" action="but_pos.htm">
          <input type="text" name="RFFE_ADDR" value="<% webmapGetParam("RFFE_ADDR"); %>" class="debug_1">
          <input type="text" name="BPM_ADDR" value="<% webmapGetParam("BPM_ADDR"); %>" class="debug_1">
          <input type="text" name="CFG_RD_ADDR"     value="<% webmapGetParam("CFG_RD_ADDR"    ); %>" class="debug_1">
          <input type="text" name="CFG_WR_ADDR"      value="<% webmapGetParam("CFG_WR_ADDR"     ); %>" class="debug_1">
          <input type="text" name="CFG_SN_ADDR"  value="<% webmapGetParam("CFG_SN_ADDR" ); %>" class="debug_1">
          <input type="text" name="ADC_ADDR"     value="<% webmapGetParam("ADC_ADDR"    ); %>" class="debug_1">
          <input type="text" name="BPM_COMM_ADDR"  value="<% webmapGetParam("BPM_COMM_ADDR" ); %>" class="debug_1">
          <input type="text" name="QDR_ADDR"  value="<% webmapGetParam("QDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DDR_ADDR"  value="<% webmapGetParam("DDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DEVICE"       value="<% webmapGetParam("DEVICE"      ); %>" class="debug_1">
          <input type="submit" class="menu_button" value="Position" title="but_pos" id="menu_bpm" style="width:80px">
        </form>
      </td>
      <td>
        <form method="get" action="adc12fl.htm">
          <input type="text" name="RFFE_ADDR" value="<% webmapGetParam("RFFE_ADDR"); %>" class="debug_1">
          <input type="text" name="BPM_ADDR" value="<% webmapGetParam("BPM_ADDR"); %>" class="debug_1">
          <input type="text" name="CFG_RD_ADDR"     value="<% webmapGetParam("CFG_RD_ADDR"    ); %>" class="debug_1">
          <input type="text" name="CFG_WR_ADDR"      value="<% webmapGetParam("CFG_WR_ADDR"     ); %>" class="debug_1">
          <input type="text" name="CFG_SN_ADDR"  value="<% webmapGetParam("CFG_SN_ADDR" ); %>" class="debug_1">
          <input type="text" name="ADC_ADDR"     value="<% webmapGetParam("ADC_ADDR"    ); %>" class="debug_1">
          <input type="text" name="BPM_COMM_ADDR"  value="<% webmapGetParam("BPM_COMM_ADDR" ); %>" class="debug_1">
          <input type="text" name="QDR_ADDR"  value="<% webmapGetParam("QDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DDR_ADDR"  value="<% webmapGetParam("DDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DEVICE"       value="<% webmapGetParam("DEVICE"      ); %>" class="debug_1">
          <input type="submit" class="menu_button" value="ADC" title="adc12fl.htm" id="menu_bpm" style="width:80px">
        </form>
      </td>
      <td>
        <form method="get" action="but_det.htm">
          <input type="text" name="RFFE_ADDR" value="<% webmapGetParam("RFFE_ADDR"); %>" class="debug_1">
          <input type="text" name="BPM_ADDR" value="<% webmapGetParam("BPM_ADDR"); %>" class="debug_1">
          <input type="text" name="CFG_RD_ADDR"     value="<% webmapGetParam("CFG_RD_ADDR"    ); %>" class="debug_1">
          <input type="text" name="CFG_WR_ADDR"      value="<% webmapGetParam("CFG_WR_ADDR"     ); %>" class="debug_1">
          <input type="text" name="CFG_SN_ADDR"  value="<% webmapGetParam("CFG_SN_ADDR" ); %>" class="debug_1">
          <input type="text" name="ADC_ADDR"     value="<% webmapGetParam("ADC_ADDR"    ); %>" class="debug_1">
          <input type="text" name="BPM_COMM_ADDR"  value="<% webmapGetParam("BPM_COMM_ADDR" ); %>" class="debug_1">
          <input type="text" name="QDR_ADDR"  value="<% webmapGetParam("QDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DDR_ADDR"  value="<% webmapGetParam("DDR_ADDR" ); %>" class="debug_1">
          <input type="text" name="DEVICE"       value="<% webmapGetParam("DEVICE"      ); %>" class="debug_1">
          <input type="submit" class="menu_button" value="Detector" title="but_det" id="menu_bpm" style="width:80px">
        </form>
      </td>
      <td>
        <form method="get" action="help.htm">
          <input type="submit" class="menu_button" value="Help" title="help.htm" id="menu_help" style="width:80px">
        </form>
      </td>
    </tr>
  </table>
</div>

