<div id="head_menu">
  <table>
    <tr>
      <td>
        <form class="forms" action="index.html">
          <input type="submit" class="menu_button" value="Main" title="index.html" id="menu_main" style="width:80px">
        </form>
      </td>
      <td>
        <form class="forms" action="gpac.htm">
          <input type="submit" class="menu_button" value="GPAC" title="gpac.htm" id="menu_gpac" style="width:80px">
        </form>
      </td>
      <td>
        <form class="forms" action="help.htm">
          <input type="submit" class="menu_button" value="Help" title="help.htm" id="menu_help" style="width:80px">
        </form>
      </td>
    </tr>
  </table>
</div>

